development:
  dialect: postgres
  database: staccato_development
  user: postgres
  password: postgres
  host: 0.0.0.0
  pool: 5
  port: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/staccato_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/staccato_production?sslmode=disable"}}