package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/jeremyliu/staccato/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Note)
// DB Table: Plural (notes)
// Resource: Plural (Notes)
// Path: Plural (/notes)
// View Template Folder: Plural (/templates/notes/)

// NotesResource is the resource for the Note model
type NotesResource struct {
	buffalo.Resource
}

// List gets all Notes. This function is mapped to the path
// GET /notes
func (v NotesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	notes := &models.Notes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Notes from the DB
	if err := q.All(notes); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, notes))
}

// Show gets the data for one Note. This function is mapped to
// the path GET /notes/{note_id}
func (v NotesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Note
	note := &models.Note{}

	// To find the Note the parameter note_id is used.
	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, note))
}

// New renders the form for creating a new Note.
// This function is mapped to the path GET /notes/new
func (v NotesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Note{}))
}

// Create adds a Note to the DB. This function is mapped to the
// path POST /notes
func (v NotesResource) Create(c buffalo.Context) error {
	// Allocate an empty Note
	note := &models.Note{}

	// Bind note to the html form elements
	if err := c.Bind(note); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(note)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, note))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Note was created successfully")

	// and redirect to the notes index page
	return c.Render(201, r.Auto(c, note))
}

// Edit renders a edit form for a Note. This function is
// mapped to the path GET /notes/{note_id}/edit
func (v NotesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Note
	note := &models.Note{}

	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, note))
}

// Update changes a Note in the DB. This function is mapped to
// the path PUT /notes/{note_id}
func (v NotesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Note
	note := &models.Note{}

	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Note to the html form elements
	if err := c.Bind(note); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(note)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, note))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Note was updated successfully")

	// and redirect to the notes index page
	return c.Render(200, r.Auto(c, note))
}

// Destroy deletes a Note from the DB. This function is mapped
// to the path DELETE /notes/{note_id}
func (v NotesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Note
	note := &models.Note{}

	// To find the Note the parameter note_id is used.
	if err := tx.Find(note, c.Param("note_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(note); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Note was destroyed successfully")

	// Redirect to the notes index page
	return c.Render(200, r.Auto(c, note))
}
