package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/jeremyliu/staccato/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Staccato)
// DB Table: Plural (staccatos)
// Resource: Plural (Staccatos)
// Path: Plural (/staccatos)
// View Template Folder: Plural (/templates/staccatos/)

// StaccatosResource is the resource for the Staccato model
type StaccatosResource struct {
	buffalo.Resource
}

// List gets all Staccatos. This function is mapped to the path
// GET /staccatos
func (v StaccatosResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	staccatos := &models.Staccatos{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Staccatos from the DB
	if err := q.All(staccatos); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, staccatos))
}

// Show gets the data for one Staccato. This function is mapped to
// the path GET /staccatos/{staccato_id}
func (v StaccatosResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Staccato
	staccato := &models.Staccato{}

	// To find the Staccato the parameter staccato_id is used.
	if err := tx.Find(staccato, c.Param("staccato_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, staccato))
}

// New renders the form for creating a new Staccato.
// This function is mapped to the path GET /staccatos/new
func (v StaccatosResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Staccato{}))
}

// Create adds a Staccato to the DB. This function is mapped to the
// path POST /staccatos
func (v StaccatosResource) Create(c buffalo.Context) error {
	// Allocate an empty Staccato
	staccato := &models.Staccato{}

	// Bind staccato to the html form elements
	if err := c.Bind(staccato); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(staccato)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, staccato))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Staccato was created successfully")

	// and redirect to the staccatos index page
	return c.Render(201, r.Auto(c, staccato))
}

// Edit renders a edit form for a Staccato. This function is
// mapped to the path GET /staccatos/{staccato_id}/edit
func (v StaccatosResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Staccato
	staccato := &models.Staccato{}

	if err := tx.Find(staccato, c.Param("staccato_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, staccato))
}

// Update changes a Staccato in the DB. This function is mapped to
// the path PUT /staccatos/{staccato_id}
func (v StaccatosResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Staccato
	staccato := &models.Staccato{}

	if err := tx.Find(staccato, c.Param("staccato_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Staccato to the html form elements
	if err := c.Bind(staccato); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(staccato)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, staccato))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Staccato was updated successfully")

	// and redirect to the staccatos index page
	return c.Render(200, r.Auto(c, staccato))
}

// Destroy deletes a Staccato from the DB. This function is mapped
// to the path DELETE /staccatos/{staccato_id}
func (v StaccatosResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Staccato
	staccato := &models.Staccato{}

	// To find the Staccato the parameter staccato_id is used.
	if err := tx.Find(staccato, c.Param("staccato_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(staccato); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Staccato was destroyed successfully")

	// Redirect to the staccatos index page
	return c.Render(200, r.Auto(c, staccato))
}
